### ISSUE TITLE
Example notebook: are the examples intended to be independent?

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/Diffraction-postprocessing#5]
There is some duplication of python imports e.g. numpy and matplotlib

Perhaps all the imports could go at the top, or the examples could be split into separate notebooks?

Similarly this variable is assigned in four different examples:
`ve_response = workflow.tasks.simulate_volume_element_loading.elements[0].outputs.volume_element_response`

**Comment by Gbowker** [comment]
commit [bdec57e](https://github.com/LightForm-group/Diffraction-postprocessing/commit/bdec57e715e2eee26d3d0af1d73ade5c210cd103) removes duplicate definitions of `ve_response` variable.
